/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "app.h"

wyjscie *
obliczenia_1_svc(wejscie *argp, struct svc_req *rqstp)
{
	static wyjscie  result;
	/*
	 * insert server code here
	 */
    printf("Otrzymane dane: %s\n",argp->dane);
    int i=0;
    int x =0;
    while(argp->dane[x] != '\0')
    {
        
        sprintf((char*)(result.wynik+i),"%02X", argp->dane[x]);
        x++;
        i+=2;
    }
    printf("w hex: %s\n",result.wynik);
	
    
    
	return &result;
}
