/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "app.h"

char wynik_g[256];
int flaga = 0;

wyjscie *
obliczenia_1_svc(wejscie *argp, struct svc_req *rqstp)
{
	static wyjscie  result;
	/*
	 * insert server code here
	 */
    printf("Otrzymane dane: %s\n",argp->dane);
    int i=0;
    int x =0;
    while(argp->dane[x] != '\0')
    {
        
        sprintf((char*)(wynik_g+i),"%02X", argp->dane[x]);
        x++;
        i+=2;
    }
    printf("w hex: %s\n",wynik_g);
    flaga =1;
    
    return &result;
}

wyjscie2 *
obliczenia2_1_svc(wejscie2 *argp, struct svc_req *rqstp)
{
    
	static wyjscie2  result;

    if(flaga==1)
    {
    int x=0;
    int n = sizeof(wynik_g);
    while(x<=n)
    {
        result.wynik2[x] = wynik_g[x];
        x++;
    }
        flaga =0;
        return &result;
    }
    else
    {
        result.wynik2[0] = '\0';
        return &result;
    }
    
}
